@echo off
xcopy ".\package\*.html" "..\..\server-files\client_packages" /E /b /v /y
echo HTML-files has been copied...
xcopy ".\package\*.css" "..\..\server-files\client_packages" /E /b /v /y
echo CSS-files has been copied...
xcopy ".\package\*.jpg" "..\..\server-files\client_packages" /E /b /v /y
echo JPG-files has been copied...
xcopy ".\package\*.png" "..\..\server-files\client_packages" /E /b /v /y
echo PNG-files has been copied...
xcopy ".\package\*.json" "..\..\server-files\client_packages" /E /b /v /y
echo JSON-files has been copied...
xcopy ".\package\*.js" "..\..\server-files\client_packages" /E /b /v /y
echo Javascript-files has been copied...
xcopy ".\package\*.svg" "..\..\server-files\client_packages" /E /b /v /y
echo SVG-files has been copied...
xcopy ".\package\*.ttf" "..\..\server-files\client_packages" /E /b /v /y
echo TTF-files has been copied...
xcopy ".\package\*.woff" "..\..\server-files\client_packages" /E /b /v /y
echo WOFF-files has been copied...
xcopy ".\package\*.mp3" "..\..\server-files\client_packages" /E /b /v /y
echo MP3-files has been copied...
xcopy ".\package\*.otf" "..\..\server-files\client_packages" /E /b /v /y
echo OTF-files has been copied...

tsc

