import "./game";
import "./game/camera";
import "./game/carshop";
import "./game/overlay";
import "./web/login/loginjs";
import "./game/inventory";
import "./game/objects";
import "./game/nametags";
import "./game/blip";
import "./game/Gangzones";
import "./game/weather";
import "./game/killcam";
import "./game/sync";
import "./web/admin/main";
import "./game/carsharing";
import "./web/leveling/index";
import "./web/playermenu/menu";
import "./game/video";
import "./game/anticheat";
import "./chat/chat";
import "./voice/chat";
import "./game/streamer";
import "./game/donate";
import "./game/player";
import "./game/animations";
import "./game/effects";
import "./web/grouping/grouping";
import "./web/grouping/object";
import "./game/juwelry";
import "./game/bankrob";
import "./game/rob";
import "./web/bounty/bounty";
import "./game/vehicle";
import "./game/weapon";
import "./game/editor";
import "./game/tattoo";
import "./game/weed";
import "./game/paintball";
import "./game/egg";
import "./game/settings";
import "./game/tuning";
import "./game/ped";
import "./game/og";
import "./game/casino";

mp.gui.chat.show(false);
var chatbox = mp.browsers.new("package://chat//index.html");
chatbox.markAsChat();
